---
# Title: Apache Guacamole Server
#
# Author: Bitfinity / L. Rutten
# Owner: Bitfinity / L. Rutten
#
# File: ansible-pull.yml
#
# Description:
#   Apache Guacamole is a clientless remote desktop gateway.
#   It supports standard protocols like VNC, RDP, and SSH.
# 
# Source(s):
#   - https://guacamole.apache.org/
#   - https://guacamole.apache.org/doc/gug/ldap-auth.html#preparing-your-ldap-directory-optional
#
- hosts: localhost
  connection: local
  become: true
  
  pre_tasks:
    - name: "Include defaults file ~/.ansible-config.yml"
      include_vars: ~/.ansible-config.yml  
  
  vars:
  
  handlers:
    - include: handlers/main.yml
  
  roles:
    - role-automatic-updates
  
  tasks:
    - name: "Include tasks/01-base.yml"
      include_tasks: tasks/01-base.yml    
