---
# Title: Apache Guacamole Server
#
# Author: Bitfinity / L. Rutten
# Owner: Bitfinity / L. Rutten
#
# File: handlers/main.yml
#
# Description:
#   Apache Guacamole is a clientless remote desktop gateway.
#   It supports standard protocols like VNC, RDP, and SSH.
# 
