---
# Title: Apache Guacamole Server
#
# Author: Bitfinity / L. Rutten
# Owner: Bitfinity / L. Rutten
#
# File: handlers/main.yml
#
# Description:
#   Apache Guacamole is a clientless remote desktop gateway.
#   It supports standard protocols like VNC, RDP, and SSH.
# 
- name: "restart_apache2"
  systemd:
    state: restarted
    daemon_reload: yes
    enabled: yes
    name: apache2
    
- name: "reload_apache2"
  systemd:
    daemon_reload: yes
    name: apache2

- name: "restart_docker_container_guacamole"
  community.docker.docker_container:
    name: guacamole
    restart: true
    #container_default_behavior: compatibility
