---
# Title: Apache Guacamole Server
#
# Author: Bitfinity / L. Rutten
# Owner: Bitfinity / L. Rutten
#
# File: ansible-pull.yml
#
# Description:
#   Apache Guacamole is a clientless remote desktop gateway.
#   It supports standard protocols like VNC, RDP, and SSH.
#
- hosts: localhost
  connection: local
  become: true
  
  pre_tasks:
    - name: "Include defaults file ~/.ansible-config.yml"
      include_vars: ~/.ansible-config.yml  
  
  vars:
  
  handlers:
    - include: handlers/main.yml
  
  roles:
    - role-apache-guacamole-gateway
  
  tasks:
    - name: "Configure firewall profile and enable for ssh (22/tcp) and bruteforce protection"
      community.general.ufw:
        rule: limit
        name: OpenSSH
        state: enabled
