---
# Title: Apache Guacamole Server
#
# Author: Bitfinity / L. Rutten
# Owner: Bitfinity / L. Rutten
#
# File: tasks/dockers/2404/00-maintenance.yml
#
# Description:
#   Apache Guacamole is a clientless remote desktop gateway.
#   It supports standard protocols like VNC, RDP, and SSH.
# 
- name: "Check if docker container 'guacamole' is running on host '{{ ansible_host }}'" 
  ansible.builtin.raw: if [ -n "$(docker ps -f "name=^/guacamole$" -f "status=running" -q )" ]; then echo "running"; fi
  register: result_status_container

- name: "Stop docker container 'guacamole' on host '{{ ansible_host }}'"
  community.docker.docker_container:
    name: guacamole
    state: stopped
  when: result_status_container.stdout_lines == "running"

- name: "Prune everything (including non-dangling images) on host '{{ ansible_host }}'"
  community.docker.docker_prune:
    containers: true
    images: true
    images_filters:
      dangling: false
    networks: true
    volumes: true
    builder_cache: true
  when: result_status_container.stdout_lines == "running"
