---
# Title: Apache Guacamole Server
#
# Author: Bitfinity / L. Rutten
# Owner: Bitfinity / L. Rutten
#
# File: tasks/dockers/01-apache-guacamole.yml
#
# Description:
#   Apache Guacamole is a clientless remote desktop gateway.
#   It supports standard protocols like VNC, RDP, and SSH.
# 
# Source(s):
#   - https://www.howtoforge.com/how-to-install-apache-guacamole-as-docker-container-on-ubuntu/
#

- name: "Install APT packages (Dependencies)"
  ansible.builtin.apt:
    pkg:
    - ca-certificates
    - curl
    - gnupg
    - lsb-release

- name: "Add Docker GPG Key"
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor > /etc/apt/trusted.gpg.d/docker-archive-keyring.gpg

- name: "Add Docker repository"
echo "deb [arch=$(dpkg --print-architecture)] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list

- name: "Install APT packages - Docker Engine Package"
  ansible.builtin.apt:
    pkg:
    - docker-ce 
    - docker-ce-cli
    - containerd.io
    
    
