---
# Title: Apache Guacamole Server
#
# Author: Bitfinity / L. Rutten
# Owner: Bitfinity / L. Rutten
#
# File: tasks/docker/02-apache2.yml
#
# Description:
#   Apache Guacamole is a clientless remote desktop gateway.
#   It supports standard protocols like VNC, RDP, and SSH.
# 
- name: "Install APT packages"
  ansible.builtin.apt:
    pkg:
    - apache2

- name: "Apache2 load modules"
  apache2_module:
    state: present
    name: "{{ item }}"
  with_items:
    - proxy
    - proxy_http
    - rewrite
    - ssl
    
- name: "Transfer templates"
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: 'templates/apache2.conf.j2', dest: '/etc/apache2/sites-available/{{ guac_apache2_application_name }}.conf' }

- name: "Disable "
  command: "a2dissite {{ item }}"
  with_items:
    - 000-default.conf
    - default-ssl.conf 
    - 000-default-le-ssl.conf
  notify:
    - restart_apache2

- name: "Enable {{ guac_apache2_application_name }}.conf"
  command: a2ensite {{ guac_apache2_application_name }}.conf
  notify: restart_apache2

- name: "Configure UFW for Apache2 Webserver"
  community.general.ufw:
    rule: allow
    name: Apache Full
  
